name: api_queue_handler
description: "Queue up your API requests effortlessly, ensuring they are processed one after the other."
version: 1.0.5
homepage: https://github.com/thehelmsdeep/api_queue_handler

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^1.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

